.\" Manpage for args.c and args.h
.TH man 8 "25 June 2024" "1.0" "argument parser man page"
.SH NAME
argument parser
.SH SYNOPSIS
designed to process arguments from the terminal into neat lists
.SH DESCRIPTION
uses a struct to hold details of each type of argument sent.
.SH SEE ALSO
Nothing currently. 
.SH BUGS
No known bugs.
.SH AUTHOR
rufus173
