#include <stdio.h>
#include <getopt.h>
#include <stdlib.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <netdb.h>
#include <string.h>

#define PORT 19532
#define STRING(x) #x

enum action {
	ACTION_UNLOCK = 0,
	ACTION_LOCK,
};

struct auth_request {
	uint64_t action; //enum action
};
struct auth_challenge {
	char entropy[64]; //random data generated by remoteunlockd
};
struct auth_response {
	char digest[64]; //sha256(entropy | secret_key)
};

/*
client         remoteunlockd     
  |                 |                                +----------+
  |  auth_request   |            auth_challenge ---> |  auth()  | ---> auth_response
  |---------------->|                                +----------+
  |                 |            
  |  auth_challenge |                         "|" = concatenate, `secret_key` is a pre shared key both the client and remoteunlockd know
  |<----------------|                   auth(auth_challenge){
  |                 |                       struct auth_response auth_response
  |  auth_response  |                       auth_response.digest = sha256(auth_challenge.entropy | secret_key)
  |---------------->|                       return auth_response
  |                 |                   }
*/

int main(int argc, char **argv){
	const struct option long_options[] = {
		{"unlock-command",required_argument,NULL,'c'},
		{0,0,0,0}
	};
	char unlock_command[1024] = {0};
	//====== digest command line ======
	for (;;){
		int option_index = 0;
		int result = getopt_long(argc,argv,"c:",long_options,&option_index);
		if (result == -1) break;
		switch (result){
		case 'c':
			strncpy(unlock_command,optarg,sizeof(unlock_command)-1);
			break;
		}
	}
	//====== setup network ======
	//getaddrinfo
	struct addrinfo hints = {
		.ai_socktype = SOCK_STREAM,
		.ai_flags = AI_PASSIVE,
	};
	struct addrinfo *address_info = NULL;
	int result = getaddrinfo(NULL,STRING(PORT),&hints,&address_info);
	if (result < 0){
		fprintf(stderr,"getaddrinfo: %s\n",gai_strerror(result));
		return EXIT_FAILURE;
	}
	//socket
	int sockfd = socket(address_info->ai_family,address_info->ai_socktype,0);
	if (sockfd < 0){
		perror("socket");
		freeaddrinfo(address_info);
		return EXIT_FAILURE;
	}
	//bind and listen
	result = bind(sockfd,address_info->ai_addr,address_info->ai_addrlen);
	//no longer needed
	freeaddrinfo(address_info);
	//validate bind
	if (result < 0){
		perror("bind");
		close(sockfd);
		return EXIT_FAILURE;
	}
	result = listen(sockfd,10);
	if (result != 0){
		perror("listen");
		close(sockfd);
		return EXIT_FAILURE;
	}
	//====== listen for new connections ======
	for (;;){
		//accept
		int connection = accept(sockfd,NULL,NULL);
		if (connection < 0){
			perror("accept");
			continue;
		}
		//cleanup
		close(connection);
	}
	return 0;
}
