#include <stdio.h>
#include <getopt.h>
#include <stdlib.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <netdb.h>
#include <string.h>
#include "../../../source-code/base_n.h"
#include "../../../source-code/crypto.h"
#include <alloca.h>

#define PORT 19532
#define STRING(x) S(x)
#define S(x) #x

enum action {
	ACTION_UNLOCK = 0,
	ACTION_LOCK,
};

struct __attribute__((packed)) auth_request {
	uint64_t action; //enum action
};
struct __attribute__((packed)) auth_challenge {
	char entropy[64]; //random data generated by remoteunlockd
};
struct __attribute__((packed)) auth_response {
	char digest[32]; //sha256(entropy | secret_key)
};
struct __attribute__((packed)) request_status {
	uint8_t status;
	//0 - success
	//1 - auth failure
	//2 - unknown request
	//3 - server error
};

/*
client         remoteunlockd     
  |                 |                                +----------+
  |  auth_request   |            auth_challenge ---> |  auth()  | ---> auth_response
  |---------------->|                                +----------+
  |                 |            
  |  auth_challenge |                         "|" = concatenate, `secret_key` is a pre shared key both the client and remoteunlockd know
  |<----------------|                   auth(auth_challenge){
  |                 |                       struct auth_response auth_response
  |  auth_response  |                       auth_response.digest = sha256(auth_challenge.entropy | secret_key)
  |---------------->|                       return auth_response
  |                 |                   }
  | request_status  |
  |<----------------|
  |                 |
*/

void print_help(void);

int main(int argc, char **argv){
	const struct option long_options[] = {
		{"unlock-command",required_argument,0,'u'},
		{"lock-command",required_argument,0,'l'},
		{"secret-key",required_argument,0,'k'},
		{"help",no_argument,0,'h'},
		{0,0,0,0}
	};
	char commands[2][1024] = {0};
	char *secret_key = NULL;
	ssize_t secret_key_len = 0;
	//====== digest command line ======
	for (;;){
		int option_index = 0;
		int result = getopt_long(argc,argv,"u:l:k:h",long_options,&option_index);
		if (result == -1) break;
		switch (result){
		case 'u':
			strncpy(commands[ACTION_UNLOCK],optarg,sizeof(commands[ACTION_UNLOCK])-1);
			break;
		case 'l':
			strncpy(commands[ACTION_LOCK],optarg,sizeof(commands[ACTION_LOCK])-1);
			break;
		case 'k':
			secret_key = alloca((strlen(optarg)*5)/8);
			secret_key_len = base32_decode(optarg,strlen(optarg),secret_key);
			if (secret_key_len < 0){
				fprintf(stderr,"secret key not valid base 32\n");
				return EXIT_FAILURE;
			}
			break;
		case 'h':
			print_help();
			return EXIT_SUCCESS;
		}
	}
	if (secret_key == NULL){
		fprintf(stderr,"Please provide a secret key (see --help for help)\n");
		return EXIT_FAILURE;
	}
	//====== setup network ======
	//getaddrinfo
	struct addrinfo hints = {
		.ai_socktype = SOCK_STREAM,
		.ai_family = AF_UNSPEC,
		.ai_flags = AI_PASSIVE,
	};
	struct addrinfo *address_info = NULL;
	int result = getaddrinfo(NULL,STRING(PORT),&hints,&address_info);
	if (result < 0){
		fprintf(stderr,"getaddrinfo: %s\n",gai_strerror(result));
		return EXIT_FAILURE;
	}
	//socket
	int sockfd = socket(address_info->ai_family,address_info->ai_socktype,0);
	if (sockfd < 0){
		perror("socket");
		freeaddrinfo(address_info);
		return EXIT_FAILURE;
	}
	//bind and listen
	result = bind(sockfd,address_info->ai_addr,address_info->ai_addrlen);
	//no longer needed
	freeaddrinfo(address_info);
	//validate bind
	if (result < 0){
		perror("bind");
		close(sockfd);
		return EXIT_FAILURE;
	}
	result = listen(sockfd,10);
	if (result != 0){
		perror("listen");
		close(sockfd);
		return EXIT_FAILURE;
	}
	//====== listen for new connections ======
	for (;;){
		//====== accept ======
		int connection = accept(sockfd,NULL,NULL);
		if (connection < 0){
			perror("accept");
			continue;
		}
		printf("new connection\n");
		//====== auth_request ======
		struct auth_request request = {0};
		if (recv(connection,&request,sizeof(request),0) < 0){
			perror("recv");
			fprintf(stderr,"auth request not received\n");
			goto cleanup;
		}
		unsigned long requested_action = ntohl(request.action);
		printf("requested action: %lu\n",requested_action);
		//====== auth_challenge ======
		struct auth_challenge challenge = {0};
		//get random data
		getentropy(&challenge.entropy,sizeof(challenge.entropy));
		if (send(connection,&challenge,sizeof(challenge),0) < 0){
			perror("send");
			fprintf(stderr,"auth challenge could not be sent\n");
			goto cleanup;
		}
		//====== auth_response ======
		struct auth_response response = {0};
		if (recv(connection,&response,sizeof(response),0) < 0){
			perror("recv");
			fprintf(stderr,"auth response not received\n");
			goto cleanup;
		}
		//====== validate response ======
		int auth_status = 0;
		//TODO TODO TODO
		//concatenate entropy and secret key
		char *hash_input = alloca(64+secret_key_len);
		memcpy(hash_input,&challenge.entropy,sizeof(challenge.entropy));
		memcpy(hash_input+64,secret_key,secret_key_len);
		unsigned char digest[32] = {0};
		//hash result
		sha256(hash_input,64+secret_key_len,digest);
		//compare hashes
		if (memcmp(digest,&response.digest,32) == 0){
			printf("authentication successfull\n");
			auth_status = 1;
		}else {
			fprintf(stderr,"authentication failed (missmatched hash values)\n");
			auth_status = 0;
		}
		//====== perform action ======
		int action_status = 0;
		if (auth_status == 1 && requested_action < sizeof(commands)/sizeof(commands[0])){
			printf("executing \"%s\"\n",commands[requested_action]);
			system(commands[requested_action]);
		}else {
			action_status = 1;
		}
		//====== request_status ======
		struct request_status status = {
			.status = action_status,
		};
		if (send(connection,&status,sizeof(status),0) < 0){
			perror("send");
			fprintf(stderr,"request status could not be sent\n");
			goto cleanup;
		}
		printf("%s\n",(action_status == 0) ? "request successfull" : "request failed");
		//====== cleanup ======
		cleanup:
		close(connection);
		printf("connection closed\n");
	}
	return 0;
}

void print_help(){
	printf("usage: remoteunlockd [options]\n");
	printf("options:\n");
	printf("	-h, --help                 : show this help text\n");
	printf("	-k, --secret-key <key>     : provide the base32 secret key to use\n");
	printf("	-u, --unlock-command <cmd> : run this command when unlock is requested\n");
	printf("	-l, --lock-command <cmd>   : run this command when lock is requested\n");
	printf("instructions:\n");
	printf("pick a random secret key to use for both the mobile app and daemon.\n");
	printf("when the mobile app requests an action, if the secret keys match, it will run the relevant command.\n");
}
