#include <stdio.h>
#include <getopt.h>
#include <stdlib.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <netdb.h>
#include <string.h>

#define PORT 19532
#define STRING(x) S(x)
#define S(x) #x

enum action {
	ACTION_UNLOCK = 0,
	ACTION_LOCK,
};

struct __attribute__((packed)) auth_request {
	uint64_t action; //enum action
};
struct __attribute__((packed)) auth_challenge {
	char entropy[64]; //random data generated by remoteunlockd
};
struct __attribute__((packed)) auth_response {
	char digest[32]; //sha256(entropy | secret_key)
};
struct __attribute__((packed)) request_status {
	uint8_t status;
	//0 - success
	//1 - auth failure
	//2 - unknown request
	//3 - server error
};

/*
client         remoteunlockd     
  |                 |                                +----------+
  |  auth_request   |            auth_challenge ---> |  auth()  | ---> auth_response
  |---------------->|                                +----------+
  |                 |            
  |  auth_challenge |                         "|" = concatenate, `secret_key` is a pre shared key both the client and remoteunlockd know
  |<----------------|                   auth(auth_challenge){
  |                 |                       struct auth_response auth_response
  |  auth_response  |                       auth_response.digest = sha256(auth_challenge.entropy | secret_key)
  |---------------->|                       return auth_response
  |                 |                   }
  | request_status  |
  |<----------------|
  |                 |
*/

int main(int argc, char **argv){
	const struct option long_options[] = {
		{"unlock-command",required_argument,NULL,'c'},
		{0,0,0,0}
	};
	char unlock_command[1024] = {0};
	//====== digest command line ======
	for (;;){
		int option_index = 0;
		int result = getopt_long(argc,argv,"c:",long_options,&option_index);
		if (result == -1) break;
		switch (result){
		case 'c':
			strncpy(unlock_command,optarg,sizeof(unlock_command)-1);
			break;
		}
	}
	//====== setup network ======
	//getaddrinfo
	struct addrinfo hints = {
		.ai_socktype = SOCK_STREAM,
		.ai_family = AF_UNSPEC,
		.ai_flags = AI_PASSIVE,
	};
	struct addrinfo *address_info = NULL;
	int result = getaddrinfo(NULL,STRING(PORT),&hints,&address_info);
	if (result < 0){
		fprintf(stderr,"getaddrinfo: %s\n",gai_strerror(result));
		return EXIT_FAILURE;
	}
	//socket
	int sockfd = socket(address_info->ai_family,address_info->ai_socktype,0);
	if (sockfd < 0){
		perror("socket");
		freeaddrinfo(address_info);
		return EXIT_FAILURE;
	}
	//bind and listen
	result = bind(sockfd,address_info->ai_addr,address_info->ai_addrlen);
	//no longer needed
	freeaddrinfo(address_info);
	//validate bind
	if (result < 0){
		perror("bind");
		close(sockfd);
		return EXIT_FAILURE;
	}
	result = listen(sockfd,10);
	if (result != 0){
		perror("listen");
		close(sockfd);
		return EXIT_FAILURE;
	}
	//====== listen for new connections ======
	for (;;){
		//====== accept ======
		int connection = accept(sockfd,NULL,NULL);
		if (connection < 0){
			perror("accept");
			continue;
		}
		printf("new connection\n");
		//====== auth_request ======
		struct auth_request request = {0};
		if (recv(connection,&request,sizeof(request),0) < 0){
			perror("recv");
			fprintf(stderr,"auth request not received\n");
			goto cleanup;
		}
		int requested_action = ntohl(request.action);
		//====== auth_challenge ======
		struct auth_challenge challenge = {0};
		//get random data
		getentropy(&challenge.entropy,sizeof(challenge.entropy));
		if (send(connection,&challenge,sizeof(challenge),0) < 0){
			perror("send");
			fprintf(stderr,"auth challenge could not be sent\n");
			goto cleanup;
		}
		//====== auth_response ======
		struct auth_response response = {0};
		if (recv(connection,&challenge,sizeof(response),0) < 0){
			perror("recv");
			fprintf(stderr,"auth response not received\n");
			goto cleanup;
		}
		//====== validate response ======
		int auth_status = 0;
		//TODO TODO TODO
		auth_status = 1; //add authentication
		//TODO TODO TODO
		//cleanup
		//====== request_status ======
		struct request_status status = {
			.status = (auth_status == 1) ? 0 : 1,
		};
		if (send(connection,&status,sizeof(status),0) < 0){
			perror("send");
			fprintf(stderr,"request status could not be sent\n");
			goto cleanup;
		}
		//====== cleanup ======
		cleanup:
		close(connection);
		printf("connection closed\n");
	}
	return 0;
}
