#!/bin/bash
old_clip="$(wl-paste 2> /dev/null)"
while :
do
	network-search -b "8999"
	ip="$(network-search -tf "8999" 2> /dev/null)"
	if [ -n "$ip" ]; then
		break
	fi
done
echo "using ip $ip"
while :
do
	for i in {1..10}
	do
		network-search -b "8999"
	done
	clip="$(wl-paste 2> /dev/null)"
	if [ "$old_clip" != "$clip" ];
	then
		echo "updating other clipboard"
		old_clip="$clip"
		echo "$clip" | network-pipe 9000
		echo "done"
	fi
	newclip="$(network-pipe -q "$ip" 9000)" 
	if [ -n "$newclip" ]; then
		echo "clipboard updating to $newclip"
		echo "$newclip" | wl-copy
		old_clip="$newclip"
		newclip=
	fi
	sleep 0.5
done
