#!/bin/bash
echo "checking if run as root user..."
if [ "$EUID" -ne "0" ]; then
	echo "please run as root."
	exit 1
fi
echo "copying binary to /usr/bin..."
cp rufus-text /usr/bin
echo "installing man pages..."
../../docs/man/install-man-pages > /dev/null
echo "done"
