.\" Manpage for filter-file
.TH man 8 "28 June 2024" "2.0" "filter-file man page"
.SH NAME
filter-file
.SH SYNOPSIS
Outputs a filtered version of a files contents
.SH DESCRIPTION
Can be used to output a file with aspects filtered out, such as comments, outputing only non commented lines.
.SH SYNTAX
filter-file <filename> [options]
.SH OPTIONS:
.Bl comments
.It
-c : Filters out comments
.It
-n : strip all newlines
.El
.SH SEE ALSO
Nothing currently. 
.SH BUGS
No known bugs.
.SH AUTHOR
rufus173
