.\" Manpage for rufus-text
.TH man 8 "15 August 2024" "1.0" "rufus-text man page"
.SH NAME
rufus-text
.SH SYNOPSIS
Text editor
.SH DESCRIPTION
Bare metal text editor. It has very basic features such as opening and saving files, as well as arrow navigation.
.SH OPTIONS
rufus-text [filename]
.SH SEE ALSO
Nothing currently. 
.SH BUGS
No known bugs.
.SH AUTHOR
rufus173
