.\" Manpage for systemd-controller
.TH man 8 "5 July 2024" "1.0" "systemd-controller man page"
.SH NAME
systemd-controller
.SH SYNOPSIS
Text-based user interface for systemctl
.SH DESCRIPTION
Navigated with [up] and [down] arrow keys to select units, and [tab] can be used to change function. [enter] executes command.  used to easily and visualy start, stop, enable and disable units for systemd
.SH SYNTAX
systemd-controller
.SH SEE ALSO
Nothing currently. 
.SH BUGS
If not run as root undefined behaviour may occur when changing the status of units
.SH AUTHOR
rufus173
