.\" Manpage for mail-manager
.TH man 8 "2 August 2024" "1.0" "view-mail manual page"
.SH NAME
view-mail
.SH SYNOPSIS
view mails held by the mail-manager daemon
.SH DESCRIPTION
connects to the mail-manager daemon and reads any mail it stores.
.SH SYNTAX
view-mail
.SH SEE ALSO
mail-manager
.SH BUGS
If the daemon terminates while the program is running, undefined behavior will occur
.SH AUTHOR
rufus173
